const Program = require("./Program");
const Batch = require("./Batch");
const StudentInfo = require("./Student Info/");
const AcademicRecordStudent = require("./Academic Record Student");
const Fees = require("./Fees");
const Student = require("./Student");
const Employement = require("./Employement");
const AcademicRecordEmployee = require("./Academic Record Employee");
const Courses =require("./Courses");
const Employe_Experience=require("./Employe_Experience");
const Section= require("./Section");
const Teachers=require("./Teachers");
const Lab = require("./Lab");
const Samester = require("./Samester");
const Assessment_type = require("./Assement_type");
const Assessment =require("./Assessments")
const Enrolled_Courses = require("./Enrolled_Courses");
const Enrolement = require("./Enrolement");
const Attendance =require("./Attendance");
module.exports = (app) => {
  app.use("/api/program", Program);
  app.use("/api/batch", Batch);
  app.use("/api/student_info", StudentInfo);
  app.use("/api/academic_record_student", AcademicRecordStudent);
  app.use("/api/fees", Fees);
  app.use("/api/student", Student);
  app.use("/api/employement", Employement);
  app.use("/api/academic_record_employee", AcademicRecordEmployee);
  app.use("/api/courses",Courses);
  app.use("/api/employe_experience",Employe_Experience);
  app.use("/api/section",Section);
  app.use("/api/teachers",Teachers);
  app.use("/api/lab",Lab);
  app.use("/api/samester",Samester);
  app.use("/api/assessment_type",Assessment_type);
  app.use("/api/assessment",Assessment);
  app.use("/api/enrolled_courses",Enrolled_Courses);
  app.use("/api/enrolement",Enrolement);
  app.use("/api/attendance",Attendance);

};
